/**
 * Below are the keyword metadata list that are used in the app to increase SEO performance.
 */

const keywordConstants = [
  "international innovation day",
  "international innovation day 2024",
  "ums",
  "innovation",
  "young investors",
  "international innovation day 2024",
  "register iid 2024",
  "universitas muhammadiyah surakarta",
  "universitas muhammadiyah surakarta 2024",
  "ums iid 2024",
  "iid 2024 ums",
  "inventors",
  "overlogic team",
  "overlogic 2024",
  "overlogic iid 2024",
  "overlogic ums",
  "innopa 2024",
  "overlogic software",
  "nutrition community",
  "nutrition community ums",
  "limitless innovation",
  "gdsc",
  "gdsc ums",
  "google developer - overlogic",
  "ums iid",
  "daftar ums iid",
  "pendaftaran ums iid",
  "daftar ums international innovation day",
  "pendaftaran ums international innovation day",
  "apa itu ums iid",
  "ums international innovation day",
  "ums international innovation day 2024",
  "lomba ums iid",
  "innovation talk",
  "innovation talk ums iid",
  "overlogic universe",
  "overlogic id",
  "ums id",
];

export { keywordConstants };